version: '3.9'

services:
  testbot:
    image: lexusobm/bots:testbot_v4.2
    volumes:
      - /opt/bot_test/data:/home/bot_data
    environment:
      - TT=${{ secrets.TG_TOKEN }}
      - TA=${{ secrets.TG_ADMIN }}
